name: reaction
description: A high-level wrapper for React.
version: 0.1.0
homepage: https://github.com/aemino/reaction
author: aemino <aeminodev@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  react:
    path: ../react

dev_dependencies:
  style_genshu:
    git: git://github.com/aemino/dart-style-genshu
