name: example
description: An example Reaction app.
homepage: https://github.com/aemino/reaction
author: aemino <aeminodev@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  reaction:
    path: ..
  build_runner: '>=0.8.10 <2.0.0'
  build_web_compilers: '>=0.3.6 <0.5.0'
